package de.charite.compbio.exomiser.core.factories;

import de.charite.compbio.jannovar.data.ReferenceDictionary;
import de.charite.compbio.jannovar.reference.GenomeInterval;
import de.charite.compbio.jannovar.reference.HG19RefDictBuilder;
import de.charite.compbio.jannovar.reference.PositionType;
import de.charite.compbio.jannovar.reference.Strand;
import static de.charite.compbio.jannovar.reference.Strand.FWD;
import static de.charite.compbio.jannovar.reference.Strand.REV;
import de.charite.compbio.jannovar.reference.TranscriptModel;
import de.charite.compbio.jannovar.reference.TranscriptModelBuilder;

/**
 * Allows the easy creation of transcript models from knownGenes.txt.gz lines.
 *
 * @author Manuel Holtgrewe <manuel.holtgrewe@charite.de>
 */
public class TestTranscriptModelFactory {

    private static final ReferenceDictionary refDict = HG19RefDictBuilder.build();
        
    private static final String KG_LINE_FGFR2 = "uc021pzz.1\tchr10\t-\t123237843\t123357972\t123239370\t123353331\t18\t123237843,123243211,123244908,123246867,123247504,123256045,123258008,123260339,123263303,123274630,123276832,123279492,123298105,123310803,123324015,123324951,123353222,123357475,\t123239535,123243317,123245046,123246938,123247627,123256236,123258119,123260461,123263455,123274833,123276977,123279683,123298229,123310973,123324093,123325218,123353481,123357972,\tP21802\tuc021pzz.1";
    private static final String TRANSCRIPT_SEQ_FGFR2 = "ggcggcggctggaggagagcgcggtggagagccgagcgggcgggcggcgggtgcggagcgggcgagggagcgcgcgcggccgccacaaagctcgggcgccgcggggctgcatgcggcgtacctggcccggcgcggcgactgctctccgggctggcgggggccggccgcgagccccgggggccccgaggccgcagcttgcctgcgcgctctgagccttcgcaactcgcgagcaaagtttggtggaggcaacgccaagcctgagtcctttcttcctctcgttccccaaatccgagggcagcccgcgggcgtcatgcccgcgctcctccgcagcctggggtacgcgtgaagcccgggaggcttggcgccggcgaagacccaaggaccactcttctgcgtttggagttgctccccgcaaccccgggctcgtcgctttctccatcccgacccacgcggggcgcggggacaacacaggtcgcggaggagcgttgccattcaagtgactgcagcagcagcggcagcgcctcggttcctgagcccaccgcaggctgaaggcattgcgcgtagtccatgcccgtagaggaagtgtgcagatgggattaacgtccacatggagatatggaagaggaccggggattggtaccgtaaccatggtcagctggggtcgtttcatctgcctggtcgtggtcaccatggcaaccttgtccctggcccggccctccttcagtttagttgaggataccacattagagccagaagagccaccaaccaaataccaaatctctcaaccagaagtgtacgtggctgcgccaggggagtcgctagaggtgcgctgcctgttgaaagatgccgccgtgatcagttggactaaggatggggtgcacttggggcccaacaataggacagtgcttattggggagtacttgcagataaagggcgccacgcctagagactccggcctctatgcttgtactgccagtaggactgtagacagtgaaacttggtacttcatggtgaatgtcacagatgccatctcatccggagatgatgaggatgacaccgatggtgcggaagattttgtcagtgagaacagtaacaacaagagagcaccatactggaccaacacagaaaagatggaaaagcggctccatgctgtgcctgcggccaacactgtcaagtttcgctgcccagccggggggaacccaatgccaaccatgcggtggctgaaaaacgggaaggagtttaagcaggagcatcgcattggaggctacaaggtacgaaaccagcactggagcctcattatggaaagtgtggtcccatctgacaagggaaattatacctgtgtagtggagaatgaatacgggtccatcaatcacacgtaccacctggatgttgtggagcgatcgcctcaccggcccatcctccaagccggactgccggcaaatgcctccacagtggtcggaggagacgtagagtttgtctgcaaggtttacagtgatgcccagccccacatccagtggatcaagcacgtggaaaagaacggcagtaaatacgggcccgacgggctgccctacctcaaggttctcaaggccgccggtgttaacaccacggacaaagagattgaggttctctatattcggaatgtaacttttgaggacgctggggaatatacgtgcttggcgggtaattctattgggatatcctttcactctgcatggttgacagttctgccagcgcctggaagagaaaaggagattacagcttccccagactacctggagatagccatttactgcataggggtcttcttaatcgcctgtatggtggtaacagtcatcctgtgccgaatgaagaacacgaccaagaagccagacttcagcagccagccggctgtgcacaagctgaccaaacgtatccccctgcggagacaggtaacagtttcggctgagtccagctcctccatgaactccaacaccccgctggtgaggataacaacacgcctctcttcaacggcagacacccccatgctggcaggggtctccgagtatgaacttccagaggacccaaaatgggagtttccaagagataagctgacactgggcaagcccctgggagaaggttgctttgggcaagtggtcatggcggaagcagtgggaattgacaaagacaagcccaaggaggcggtcaccgtggccgtgaagatgttgaaagatgatgccacagagaaagacctttctgatctggtgtcagagatggagatgatgaagatgattgggaaacacaagaatatcataaatcttcttggagcctgcacacaggatgggcctctctatgtcatagttgagtatgcctctaaaggcaacctccgagaatacctccgagcccggaggccacccgggatggagtactcctatgacattaaccgtgttcctgaggagcagatgaccttcaaggacttggtgtcatgcacctaccagctggccagaggcatggagtacttggcttcccaaaaatgtattcatcgagatttagcagccagaaatgttttggtaacagaaaacaatgtgatgaaaatagcagactttggactcgccagagatatcaacaatatagactattacaaaaagaccaccaatgggcggcttccagtcaagtggatggctccagaagccctgtttgatagagtatacactcatcagagtgatgtctggtccttcggggtgttaatgtgggagatcttcactttagggggctcgccctacccagggattcccgtggaggaactttttaagctgctgaaggaaggacacagaatggataagccagccaactgcaccaacgaactgtacatgatgatgagggactgttggcatgcagtgccctcccagagaccaacgttcaagcagttggtagaagacttggatcgaattctcactctcacaaccaatgaggaatacttggacctcagccaacctctcgaacagtattcacctagttaccctgacacaagaagttcttgttcttcaggagatgattctgttttttctccagaccccatgccttacgaaccatgccttcctcagtatccacacataaacggcagtgttaaaacatgaatgactgtgtctgcctgtccccaaacaggacagcactgggaacctagctacactgagcagggagaccatgcctcccagagcttgttgtctccacttgtatatatggatcagaggagtaaataattggaaaagtaatcagcatatgtgtaaagatttatacagttgaaaacttgtaatcttccccaggaggagaagaaggtttctggagcagtggactgccacaagccaccatgtaacccctctcacctgccgtgcgtactggctgtggaccagtaggactcaaggtggacgtgcgttctgccttccttgttaattttgtaataattggagaagatttatgtcagcacacacttacagagcacaaatgcagtatataggtgctggatgtatgtaaatatattcaaattatgtataaatatatattatatatttacaaggagttattttttgtattgattttaaatggatgtcccaatgcacctagaaaattggtctctctttttttaatagctatttgctaaatgctgttcttacacataatttcttaattttcaccgagcagaggtggaaaaatacttttgctttcagggaaaatggtataacgttaatttattaataaattggtaatatacaaaacaattaatcatttatagttttttttgtaatttaagtggcatttctatgcaggcagcacagcagactagttaatctattgcttggacttaactagttatcagatcctttgaaaagagaatatttacaatatatgactaatttggggaaaatgaagttttgatttatttgtgtttaaatgctgctgtcagacgattgttcttagacctcctaaatgccccatattaaaagaactcattcataggaaggtgtttcattttggtgtgcaaccctgtcattacgtcaacgcaacgtctaactggacttcccaagataaatggtaccagcgtcctcttaaaagatgccttaatccattccttgaggacagaccttagttgaaatgatagcagaatgtgcttctctctggcagctggccttctgcttctgagttgcacattaatcagattagcctgtattctcttcagtgaattttgataatggcttccagactctttggcgttggagacgcctgttaggatcttcaagtcccatcatagaaaattgaaacacagagttgttctgctgatagttttggggatacgtccatctttttaagggattgctttcatctaattctggcaggacctcaccaaaagatccagcctcatacctacatcagacaaaatatcgccgttgttccttctgtactaaagtattgtgttttgctttggaaacacccactcactttgcaatagccgtgcaagatgaatgcagattacactgatcttatgtgttacaaaattggagaaagtatttaataaaacctgttaatttttatactgacaataaaaatgtttctacagatattaatgttaacaagacaaaataaatgtcacgcaacttatttttttaataaaaaaaaaaaaaaa";
    private static final String KG_LINE_SHH2 = "uc003wmk.1\tchr7\t-\t155595557\t155604967\t155595593\t155604816\t3\t155595557,155598989,155604516,\t155596420,155599251,155604967,\tQ15465\tuc003wmk.1";
    private static final String TRANSCRIPT_SEQ_SHH2 = "gcgaggcagccagcgagggagagagcgagcgggcgagccggagcgaggaagggaaagcgcaagagagagcgcacacgcacacacccgccgcgcgcactcgcgcacggacccgcacggggacagctcggaagtcatcagttccatgggcgagatgctgctgctggcgagatgtctgctgctagtcctcgtctcctcgctgctggtatgctcgggactggcgtgcggaccgggcagggggttcgggaagaggaggcaccccaaaaagctgacccctttagcctacaagcagtttatccccaatgtggccgagaagaccctaggcgccagcggaaggtatgaagggaagatctccagaaactccgagcgatttaaggaactcacccccaattacaaccccgacatcatatttaaggatgaagaaaacaccggagcggacaggctgatgactcagaggtgtaaggacaagttgaacgctttggccatctcggtgatgaaccagtggccaggagtgaaactgcgggtgaccgagggctgggacgaagatggccaccactcagaggagtctctgcactacgagggccgcgcagtggacatcaccacgtctgaccgcgaccgcagcaagtacggcatgctggcccgcctggcggtggaggccggcttcgactgggtgtactacgagtccaaggcacatatccactgctcggtgaaagcagagaactcggtggcggccaaatcgggaggctgcttcccgggctcggccacggtgcacctggagcagggcggcaccaagctggtgaaggacctgagccccggggaccgcgtgctggcggcggacgaccagggccggctgctctacagcgacttcctcactttcctggaccgcgacgacggcgccaagaaggtcttctacgtgatcgagacgcgggagccgcgcgagcgcctgctgctcaccgccgcgcacctgctctttgtggcgccgcacaacgactcggccaccggggagcccgaggcgtcctcgggctcggggccgccttccgggggcgcactggggcctcgggcgctgttcgccagccgcgtgcgcccgggccagcgcgtgtacgtggtggccgagcgtgacggggaccgccggctcctgcccgccgctgtgcacagcgtgaccctaagcgaggaggccgcgggcgcctacgcgccgctcacggcccagggcaccattctcatcaaccgggtgctggcctcgtgctacgcggtcatcgaggagcacagctgggcgcaccgggccttcgcgcccttccgcctggcgcacgcgctcctggctgcactggcgcccgcgcgcacggaccgcggcggggacagcggcggcggggaccgcgggggcggcggcggcagagtagccctaaccgctccaggtgctgccgacgctccgggtgcgggggccaccgcgggcatccactggtactcgcagctgctctaccaaataggcacctggctcctggacagcgaggccctgcacccgctgggcatggcggtcaagtccagctgaagccggggggccgggggaggggcgcgggagggggcg";
    private static final String KG_LINE_GNRHR2 = "uc009wiv.3\tchr1\t-\t145509751\t145515899\t145509859\t145510794\t4\t145509751,145510727,145515188,145515669,\t145510278,145510938,145515409,145515899,\tQ96P88\t\tuc009wiv.3";
    private static final String TRANSCRIPT_SEQ_GNRHR2 = "atcttcgttccctgcagaaccttgacagttgaacaagtgacctcctccagaacagatggagagtctccagaagcagaggctttagtgaacgaaattcgcaataatcagctccagatcctgaaaaggagggcgaagaatcagtggccaaagctaaccgcttcatacccacacttcatcctcctcagtttctctccaggccaccatgtctgcaggcaacggcaccccttgggatgccacctggaatatcactgttcaatggctggctgtggacatcgcatgtcggacactgatgttcctgaaactaatggccacgtattctgcagctttcctgcctgtggtcattggattggaccgccaggcagcagtactcaacccgcttggatcccgttcaggtgtaaggaaacttctgggggcagcctggggacttagtttcctgcttgccttcccccagctgttcctgttccacacggtccactgagctggcccagtccctttcactcagtgtgtcaccaaaggcagcttcaaggctcaatggcaagagaccacctataacctcttcaccttctgctgcctctttctgctgccactgactgccatggccatctgctatagccgcattgtcctcagtgtgtccaggccccagacaaggaaggggagccatgcccctgctggtgaatttgccctcccccgctcctttgacaattgtccccgtgttcgtctccgggccctgagactggccctgcttatcttgctgaccttcatcctctgctggacaccttattacctactgggtatgtggtactggttctcccccaccatgctaactgaagtccctcccagcctgagccacatccttttcctcttgggcctcctcaatgctcctttggatcctctcctctatggggccttcacccttggctgccgaagagggcaccaagaacttagtatagactcttctaaagaagggtctgggagaatgctccaagaggagattcatgcctttagacagctggaagtacaaaaaactgtgacatcaagaagggcaggagaaacaaaaggcatttctataacatctatctgatcctaacagagtatgtaggaacagaatagtaagtctttagtgccataagatcttaacatctcacttctactcctgctctcctagttccccccaaaaaagaaatactga";
    private static final String KG_LINE_RBM8A = "uc001ent.2\tchr1\t+\t145507556\t145513535\t145507666\t145509211\t6\t145507556,145508015,145508206,145508474,145508915,145509165,\t145507733,145508075,145508284,145508611,145509052,145513535,\tQ9Y5S9uc001ent.2";
    private static final String TRANSCRIPT_SEQ_RBM8A = "agagttagcctttgattggtcagcttgactggcgacctttcccctctgcgacagtttcccgaggtacctagtgtctgagcggcacagacgagatctcgatcgaaggcgagatggcggacgtgctagatcttcacgaggctgggggcgaagatttcgccatggatgaggatggggacgagagcattcacaaactgaaagaaaaagcgaagaaacggaagggtcgcggctttggctccgaagaggggtcccgagcgcggatgcgtgaggattatgacagcgtggagcaggatggcgatgaacccggaccacaacgctctgttgaaggctggattctctttgtaactggagtccatgaggaagccaccgaagaagacatacacgacaaattcgcagaatatggggaaattaaaaacattcatctcaacctcgacaggcgaacaggatatctgaaggggtatactctagttgaatatgaaacatacaaggaagcccaggctgctatggagggactcaatggccaggatttgatgggacagcccatcagcgttgactggtgttttgttcggggtccaccaaaaggcaagaggagaggtggccgaagacgcagcagaagtccagaccggagacgtcgctgacaggtcctctgttgtccaggtgttctcttcaagattccatttgaccatgcagccttggacaaataggactggggtggaacttgctgtgtttatatttaatctcttaccgtatatgcgtagtatttgagttgcgaataaatgttccatttttgttttctacatttaatgttactttcctgtcctaaaattgaaagttctaaagcatagcaaggctgtatggatcattgtgaagatacttctagggactgaactctatgtatttcttttttttcttttttttgagatagagtcttgctgtgttacccagggtggattgcagctgatcatagctcactgcagcttcaaactcttgggctcaagccatccttctgcctcactgtccctagtagttgggattacaggcacatgccaccatgcccagctaaatttttaatatttttgtagagatggggtcttgctgtgttacctgggctagttatgtgagtttctatattagacatagtctcaagtttcaggtagggtttaaagtagagacactggtcagtatttcttttttggggggaactaggagagcaggagtagaagtgagatgttaagatcttatggcactaaagacttactattctgttcctacatactctgttaggatcagatagatgttatagaaatgccttttgtttctcctgcccttcttgatgtcacagttttttgtacttccagctgtctaaaggcatgaatctcctcttggagcattctcccagacccttctttagaagagtctatactaagttcttggtgccctcttcggcagccaagggtgaaggccccatagaggagaggatccaaaggagcattgaggaggcccaagaggaaaaggatgtggctcaggctgggagggacttcagttagcatggtgggggagaaccagtaccacatacccagtaggtaataaggtgtccagcagaggatgaaggtcagcaagataagcagggccagtctcagggcccggagacgaacacggggacaattgtcaaaggagcgggggagggcaaattcaccagcaggggctaggaatttagaaaatatactgtaattcagacactcagcttctgatctgagtatagggtgaattgatggaggggcatagctagtgagacagagctcacctcctacaaggaggagaatgttgcaaaccgttttccccttcccaacctgggactatatgatttcttacccccagggattatgatagaaatatgaagccaccaagtctagacttgatggtgttcaagaataaataatactgattgcctccctagtccttgtccagctaactcagctgtttataattgaagggattcaacaaaattatctctagcatcaggtgctagacatggttagaatctcaccatggtttagtgactggtagatagctattaggtaggtagataaataaatgatgctagaggcaacaggtctagggttaaggattaaggcctgggaattggagtctcaccatggctccccttccttgtctggggcctggacacactgaggacaatgcggctatagcagatggccatggcagtcagtggcagcagaaagaggcagcagaaggtgaagaggttataggtggtctcttgccattgagccttgaagctgcctttggtgacacactgagtgaaagggactgggccagctcagtggaccgtgtggaacaggaacagctggagtggagttgaggactattagaactggttcccctcaccacccaacctacccacctatgtcatactgtctcctcccaattcatccttaattccaagtgaagcagcacagtgctgagaaacagttcatccatggtgccatgttaaagaagttggaaatatatcttgaaaatcctatcttccttttaggcttgaatatgatgctgaacagtaagtttgttaaatcttggaacttaaaacaatcctgctttctcaagtactattctaacattgcgctttataagggatgatatttctaccacctcactcatatttttagctgaaatgattttcctggtatgtctgttattttgtggaaaaagaaatattgtgtaaaatgggtgctgccaaaattccaggccattttgcagggactctgaagtgacctttagtagtaatagtcttatgtgcagtaactataatggtaaagaatgttaaataataaaatttaacattttccaaatgctattgggctgcccctccccctttttgttaaattgctgggttttccaactgaatcagtaaaaactatttctgtttagagctacaaggttaaagtgcctgctttccagtaatggagattgagtcactattaatttgataaaaggtaagctcagtaggcatcagattcctagatacaaggcatttgggaaagtgattttagcagacatgagggacatttaggaaagatgaatagtttcagcctaagagaattttgtgaactgtttggagttacgatcaggctactctgagctagttgggaaatggtctttcctcttcccatctcttgcattcatatatttctaagttttttttttttttttgtttttgtgctctgcctaagaagtgcttgagaattgtgaggagtataaaaatagtcaaagctggctgggcgcggtggctcacgcctgtaatcccagcactttgggaggctgaggcgggcggatcacgaggttaggagatggagaccatcctggctaacacagtgaaaccctgtctgtactaaagatacaaaaaactagccgggcgtggtggtaggtgcctgtagtcccagctacttgggaactcgggaggctgaggcaggagaatgacctgaacccaggaggcggagcttgcagtgagcagagattgcgccattgcactccagcctgggcgacagagtaagactgtctccaaaaaaaaaaaaaataataatcaaagctcttggatttatagtttggtccacagccttgttttgatctttcctttatcctgttttattgccatttaccacgtactgtagaaacatccctttcaactgctgataacttggaaacaagcctacaaaaataagtaatttctaactactcctaatactacctataactacccctaagcccttaccactctaacgtgacattattaaattttttattttattaacactaatattttaactacaattacagcatatgggcaatacagaatttacctaaaaggatactaatttggaacaaaaaaaatcacctttcgcacatgtatcatgtcacaaccagtttgccattgaaacaaatagaggttgcaaatattgtcagattgtcaggctgtaagaaaggatgaaattcatttcccattgcatcatcttgtggcccatggatttcaagtgccttagccaaaatcatatagctagttagcagtagagccgagactcagaaaaaaacaaagtaaaacaggcagactgaaacaaaaagtcttctaattcccagtccacatgtaaaatttgcttcatataaacaaacctaattgtaaatggcactgtagcaacaggcttctttttaacacttggattggtaaaggtcttgtttgcaacatattagaagtattatttttctctttcccccccaccccacccccaacagagtctggctctgccgcccacgccggagtgcagtggtgcagtcttggctcactgcagcctccacttcccaggttcaagcaattctcgtgcctcagcctcctgagtagttgggattacaggtgctcaccactatacccggctaatttttgtatttttagtagagatggggtttcgtcatgttggccaggttggtcttaaactcctgacctcaagtgatccacccaccttggccttccaaaatgctgggattacaggcttgagccaccaggcctttctttgttcttaggagtatagtcagactaacttctagtagttatatttctaataattgaggatgtaagtaaggatcaaatcttaaatcagtataatgcattgtcattccagagataaatcctagacccttcttggcctccttctgacataattctaatcctacagtctcagagatgctgttgtatcctgccccccaaccccatgatagtgatagtggtttttgccttgaaggaattgctttgtatttagcttttccccctctagatttctagttccttttcagtattggattggatttgagatttgattaacctagtactcaggttcagatgctcgcctctttgcaattttaacactcattcgacaataaagtcagtaaaaaacacaaaaaaaaaaaaaaaa";

    /**
     * Helper function to parse a knownGenes.txt.gz line into a TranscriptModel.
     *
     * @param refDict reference dictionary
     * @param s The knownGeneList line to parse.
     */
    public static TranscriptModelBuilder parseKnownGenesLine(ReferenceDictionary refDict, String s) {
        String[] fields = s.split("\t");
        TranscriptModelBuilder result = new TranscriptModelBuilder();
        result.setAccession(fields[0]);

        int chr = refDict.getContigNameToID().get(fields[1].substring(3));

        result.setStrand(valueOf(fields[2].charAt(0)));
        GenomeInterval txRegion = new GenomeInterval(refDict, Strand.FWD, chr, Integer.parseInt(fields[3]) + 1,
                Integer.parseInt(fields[4]), PositionType.ONE_BASED);
        result.setTXRegion(txRegion);
        GenomeInterval cdsRegion = new GenomeInterval(refDict, Strand.FWD, chr, Integer.parseInt(fields[5]) + 1,
                Integer.parseInt(fields[6]), PositionType.ONE_BASED);
        result.setCDSRegion(cdsRegion);

        int exonCount = Integer.parseInt(fields[7]);
        String[] startFields = fields[8].split(",");
        String[] endFields = fields[9].split(",");
        for (int i = 0; i < exonCount; ++i) {
            GenomeInterval exonRegion = new GenomeInterval(refDict, Strand.FWD, chr, Integer.parseInt(startFields[i]) + 1,
                    Integer.parseInt(endFields[i]), PositionType.ONE_BASED);
            result.addExonRegion(exonRegion);
        }

        return result;
    }

    private static Strand valueOf(char strand) {
        return (strand == '-') ? REV : FWD;
    }

    /**
     * @return {@link TranscriptModel} for gene FGFR2.
     */
    public static TranscriptModel buildTMForFGFR2() {
        TranscriptModelBuilder builder = TestTranscriptModelFactory.parseKnownGenesLine(refDict, KG_LINE_FGFR2);
        builder.setSequence(TRANSCRIPT_SEQ_FGFR2.toUpperCase());
        builder.setGeneSymbol("FGFR2");
        builder.setGeneID("ENTREZ2263");
        return builder.build();
    }

    /**
     * @return {@link TranscriptModel} for gene SHH.
     */
    public static TranscriptModel buildTMForSHH() {
        TranscriptModelBuilder builder = TestTranscriptModelFactory.parseKnownGenesLine(refDict, KG_LINE_SHH2);
        builder.setSequence(TRANSCRIPT_SEQ_SHH2.toUpperCase());
        builder.setGeneSymbol("SHH");
        builder.setGeneID("ENTREZ6469");
        return builder.build();
    }

    /**
     * GNRHR2 overlaps with RBM8A.
     *
     * @return {@link TranscriptModel} for gene GNRHR2.
     */
    public static TranscriptModel buildTMForGNRHR2A() {
        TranscriptModelBuilder builder = TestTranscriptModelFactory.parseKnownGenesLine(refDict, KG_LINE_GNRHR2);
        builder.setSequence(TRANSCRIPT_SEQ_GNRHR2.toUpperCase());
        builder.setGeneSymbol("GNRHR2");
        builder.setGeneID("ENTREZ114814");
        return builder.build();
    }

    /**
     * RBM8A overlaps with GNRHR2.
     *
     * @return {@link TranscriptModel} for gene RBM8A.
     */
    public static TranscriptModel buildTMForRBM8A() {
        TranscriptModelBuilder builder = TestTranscriptModelFactory.parseKnownGenesLine(refDict, KG_LINE_RBM8A);
        builder.setSequence(TRANSCRIPT_SEQ_RBM8A.toUpperCase());
        builder.setGeneSymbol("RBM8A");
        builder.setGeneID("ENTREZ9939");
        return builder.build();
    }

}
