DROP TABLE IF EXISTS REGULATORY_REGIONS;

CREATE TABLE REGULATORY_REGIONS (
  CHROMOSOME   SMALLINT,
  START        INTEGER,
  "end"        INTEGER,
  FEATURE_TYPE VARCHAR(200)
);
CREATE INDEX RR1
  ON REGULATORY_REGIONS (CHROMOSOME, START, "end");


DROP TABLE IF EXISTS tad;

CREATE TABLE tad (
  chromosome SMALLINT NOT NULL,
  start      INTEGER  NOT NULL,
  "end"      INTEGER  NOT NULL,
  entrezID   INTEGER  NOT NULL,
  symbol     VARCHAR(24)
);

CREATE INDEX tad
  ON tad (chromosome, start, "end");
