DROP TABLE IF EXISTS regulatory_features;

CREATE TABLE REGULATORY_FEATURES
(
    CHROMOSOME SMALLINT,
    START INTEGER,
    "end" INTEGER,
    FEATURE_TYPE VARCHAR(200),
    TISSUE VARCHAR(200)
);
CREATE INDEX E2 ON REGULATORY_FEATURES (CHROMOSOME, START, "end");
